### ISSUE TITLE
Feature to allow immediate command submission

### ISSUE THREAD

**Issue by kwoodrg** [Rootyjr/alexbox#1]
In order to switch the currently running television program, the user must log into the server and then from the shell issue an MPV command redirected to the MPV IPC listener interface.

I propose that there be a UI interface feature or features, where the user can do one or both of the following:

1. Submit a command instantly
2. From a button on the info panel for a tile, instantly trigger execution of the commands associated with that "tile" or TV programming block

The server process would receive the command and execute it directly (not involving the database at all) using the permissions that the server process is running under.

**Comment by JustinWoodring** [comment]
Support for this was added in the following commit:   #5dd00e8
